- name: Install common utility tools
  hosts: nodes
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install utilities
      apt:
        name:
          - tmux
          - screen
          - htop
          - net-tools
          - vim
          - neovim
        state: present

